/*Codigo SQL criado por Joshua Erbe Dutra de Oliveira*/

DROP TABLE IF EXISTS agendamento;

DROP TABLE IF EXISTS sala;

DROP TABLE IF EXISTS log_operacao;

DROP TYPE IF EXISTS tipos_operacoes CASCADE;

CREATE TYPE tipos_operacoes AS ENUM ('INSERT', 'UPDATE', 'DELETE');

CREATE TABLE sala(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE agendamento(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qual_sala BIGINT NOT NULL,
    data_inicio TIMESTAMP WITH TIME ZONE NOT NULL, 
    data_fim TIMESTAMP WITH TIME ZONE NOT NULL, 
    CONSTRAINT fk_agendamento_sala FOREIGN KEY (qual_sala) REFERENCES sala(id),
    CONSTRAINT verificar_data CHECK (data_fim > data_inicio)
);

CREATE TABLE log_operacao(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_tabela VARCHAR(50) NOT NULL, 
    tipo_operacao tipos_operacoes NOT NULL,
    data_operacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL 
);

/*Funcionamento do log de operações*/

CREATE OR REPLACE FUNCTION inserirlog()
RETURNS TRIGGER
AS $$
    BEGIN
        INSERT INTO log_operacao(nome_tabela, tipo_operacao)
        VALUES (TG_TABLE_NAME, TG_OP);

        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;

        RETURN NEW;
    END
$$ LANGUAGE plpgsql;

CREATE TRIGGER log_sala
    AFTER
    INSERT OR DELETE OR UPDATE
ON sala
    FOR EACH ROW
EXECUTE FUNCTION
    inserirlog();

CREATE TRIGGER log_agendamento
    AFTER
    INSERT OR DELETE OR UPDATE
ON agendamento
    FOR EACH ROW
EXECUTE FUNCTION
    inserirlog();

/*Triggers Agendamento*/

CREATE OR REPLACE FUNCTION bloquearexcluir()
RETURNS TRIGGER
AS $$
    BEGIN
        IF EXISTS (
            SELECT id
            FROM agendamento
            WHERE agendamento.qual_sala = OLD.id and 
            agendamento.data_fim > CURRENT_TIMESTAMP
        ) THEN
            RAISE EXCEPTION 'Não é possivel apagar uma sala agendada! Por favor, revise os agendamentos programados';
        END IF;

        RETURN OLD;
    END
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION bloquearigualdade()
RETURNS TRIGGER
AS $$
    BEGIN
        IF EXISTS (
            SELECT id
            FROM agendamento
            WHERE agendamento.id != NEW.id and 
            agendamento.qual_sala = NEW.qual_sala and
            agendamento.data_inicio < NEW.data_fim and 
            agendamento.data_fim > NEW.data_inicio
        ) THEN
            RAISE EXCEPTION 'A data escolhida ja esta agendada para a sala! Por favor, escolha uma nova data ou uma nova sala';
        END IF;

        RETURN NEW;
    END
$$ LANGUAGE plpgsql;

CREATE TRIGGER excluir_agendamento
    BEFORE
    DELETE
ON sala
    FOR EACH ROW
EXECUTE FUNCTION
    bloquearexcluir();

CREATE TRIGGER agendamentos_iguais
    BEFORE
    INSERT OR UPDATE
ON agendamento
    FOR EACH ROW
EXECUTE FUNCTION
    bloquearigualdade();
