/*Codigo SQL criado por Joshua Erbe Dutra de Oliveira*/

SET TIME ZONE 'America/Sao_Paulo';

DROP TABLE IF EXISTS agendamento;

DROP TABLE IF EXISTS sala;

DROP TABLE IF EXISTS log_operacao;

DROP TYPE IF EXISTS tipos_operacoes CASCADE;

CREATE TYPE tipos_operacoes AS ENUM ('INSERT', 'UPDATE', 'DELETE');

CREATE TABLE sala(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX idx_sala_nome_lower ON sala (LOWER(nome));

CREATE TABLE agendamento(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qual_sala BIGINT NOT NULL,
    data_inicio TIMESTAMP WITH TIME ZONE NOT NULL, 
    data_fim TIMESTAMP WITH TIME ZONE NOT NULL, 
    CONSTRAINT fk_agendamento_sala FOREIGN KEY (qual_sala) REFERENCES sala(id) ON DELETE RESTRICT
);

CREATE TABLE log_operacao(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_tabela VARCHAR(50) NOT NULL, 
    tipo_operacao tipos_operacoes NOT NULL,
    data_operacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL 
);

/*Funcionamento do log de operações*/

CREATE OR REPLACE FUNCTION fn_inserirlog()
RETURNS TRIGGER
AS $$
    BEGIN
        INSERT INTO log_operacao(nome_tabela, tipo_operacao)
        VALUES (TG_TABLE_NAME, TG_OP::tipos_operacoes);

        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;

        RETURN NEW;
    END
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_log_sala
    AFTER
    INSERT OR DELETE OR UPDATE
ON sala
    FOR EACH ROW
EXECUTE FUNCTION
    fn_inserirlog();

CREATE TRIGGER tr_log_agendamento
    AFTER
    INSERT OR DELETE OR UPDATE
ON agendamento
    FOR EACH ROW
EXECUTE FUNCTION
    fn_inserirlog();

/*Triggers Agendamento*/

CREATE OR REPLACE FUNCTION fn_bloquearexcluir()
RETURNS TRIGGER
AS $$
    BEGIN
        IF EXISTS (
            SELECT id
            FROM agendamento
            WHERE agendamento.qual_sala = OLD.id and 
            agendamento.data_fim > CURRENT_TIMESTAMP
        ) THEN
            RAISE EXCEPTION 'Não é possivel apagar uma sala agendada! Por favor, revise os agendamentos programados';
        END IF;

        RETURN OLD;
    END
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_bloquearigualdade()
RETURNS TRIGGER
AS $$
    BEGIN
        IF TG_OP = 'INSERT' THEN
            IF EXISTS (
                SELECT id
                FROM agendamento
                WHERE agendamento.qual_sala = NEW.qual_sala and
                agendamento.data_inicio < NEW.data_fim and 
                agendamento.data_fim > NEW.data_inicio
            ) THEN
                RAISE EXCEPTION 'A data escolhida ja esta agendada para a sala! Por favor, escolha uma nova data ou uma nova sala';
            END IF;
        ELSIF TG_OP = 'UPDATE' THEN
            IF EXISTS (
                SELECT id
                FROM agendamento
                WHERE agendamento.id != NEW.id and 
                agendamento.qual_sala = NEW.qual_sala and
                agendamento.data_inicio < NEW.data_fim and 
                agendamento.data_fim > NEW.data_inicio
            ) THEN
                RAISE EXCEPTION 'A data escolhida ja esta agendada para a sala! Por favor, escolha uma nova data ou uma nova sala';
            END IF; 
        END IF;

        RETURN NEW;
    END
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_excluir_agendamento
    BEFORE
    DELETE
ON sala
    FOR EACH ROW
EXECUTE FUNCTION
    fn_bloquearexcluir();

CREATE TRIGGER tr_agendamentos_iguais
    BEFORE
    INSERT OR UPDATE
ON agendamento
    FOR EACH ROW
EXECUTE FUNCTION
    fn_bloquearigualdade();

/*Tratamento de erros em caso de nome duplicado*/

CREATE OR REPLACE FUNCTION fn_bloquear_nome_duplicado()
RETURNS TRIGGER
AS $$
	BEGIN
		IF TG_OP = 'INSERT' THEN
			IF EXISTS(
				SELECT id
				FROM sala
				WHERE REPLACE(TRIM(LOWER(NEW.nome)), ' ', '') = REPLACE(TRIM(LOWER(sala.nome)), ' ', '')
				) THEN 
					RAISE EXCEPTION 'Esse nome ja esta em uso! Por favor, verifique as salas existentes';
			END IF;
		ELSIF TG_OP = 'UPDATE' THEN
			IF EXISTS(
				SELECT id
				FROM sala
				WHERE REPLACE(TRIM(LOWER(NEW.nome)), ' ', '') = REPLACE(TRIM(LOWER(sala.nome)), ' ', '') and New.ID != sala.ID
				) THEN 
					RAISE EXCEPTION 'Esse nome ja esta em uso! Por favor, verifique as salas existentes';
			END IF;
		END IF;

		RETURN NEW;
	END
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_nome_duplicado
	BEFORE
	INSERT OR UPDATE
ON sala
	FOR EACH ROW
EXECUTE FUNCTION
	fn_bloquear_nome_duplicado();

/*Tratamento de Erros Data*/

CREATE OR REPLACE FUNCTION fn_bloquear_data_passado()
RETURNS TRIGGER
AS $$
	BEGIN
		IF NEW.data_inicio < CURRENT_TIMESTAMP THEN
			RAISE EXCEPTION 'Não é possivel agendar a sala para uma data passada! Verifique novamente a data inserida';
		END IF;

        IF TG_OP = 'UPDATE' AND NEW.data_inicio = OLD.data_inicio THEN
			RETURN NEW;
		END IF;

		RETURN NEW;
	END
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_data_passado
	BEFORE
	INSERT OR UPDATE
ON agendamento
	FOR EACH ROW
EXECUTE FUNCTION
	fn_bloquear_data_passado();

CREATE OR REPLACE FUNCTION fn_bloquear_discrepancia_data()
RETURNS TRIGGER
AS $$
    BEGIN
        IF NEW.data_fim < NEW.data_inicio THEN
            RAISE EXCEPTION 'Verifique novamente as datas inseridas!';
        END IF;

        RETURN NEW; 
    END
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_datas_discrepantes
    BEFORE
    INSERT OR UPDATE
on agendamento
    FOR EACH ROW
EXECUTE FUNCTION
    fn_bloquear_discrepancia_data();

/*Tratamento de Erro nome "vazio"*/

CREATE OR REPLACE FUNCTION fn_bloquear_nomes_vazio()
RETURNS TRIGGER
AS $$
	BEGIN
		IF TRIM(NEW.nome) = '' THEN
			RAISE EXCEPTION 'Por favor, digite um nome para a sala';
		END IF;

		RETURN NEW;
	END
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_nome_vazio
	BEFORE
	INSERT OR UPDATE
ON sala
	FOR EACH ROW
EXECUTE FUNCTION
	fn_bloquear_nomes_vazio();